<Project>
	<Import Project="$(MSBuildThisFileDirectory)\eng\AdditionalFiles.props" />
	<Import Project="$(MSBuildThisFileDirectory)\eng\CurrentVersion.props" />
	<Import Project="$(MSBuildThisFileDirectory)\eng\PackageMetadata.props" />

	<!-- Generic properties -->
	<PropertyGroup>
		<ProduceReferenceAssembly>false</ProduceReferenceAssembly>
		<IncludeSourceRevisionInInformationalVersion>true</IncludeSourceRevisionInInformationalVersion>

		<ImplicitUsings>enable</ImplicitUsings>
		<LangVersion>14.0</LangVersion>
		<Nullable>enable</Nullable>
		<AllowUnsafeBlocks>true</AllowUnsafeBlocks>

		<Configurations>Debug;Release</Configurations>
		<Platform>AnyCPU</Platform>

		<IsWeb>$(TargetFramework.Contains('browserwasm'))</IsWeb>

		<!--
		Remove build warnings:
			NU1507: Warning when there are multiple package sources when using CPM with no source mapping
			NETSDK1201: Warning that specifying RID won't create self containing app
			PRI257: Ignore default language (en) not being one of the included resources (eg en-us, en-uk)
		-->
		<NoWarn>$(NoWarn);NU1507;NETSDK1201;PRI257</NoWarn>
	</PropertyGroup>
	
	<!-- Directories -->
	<PropertyGroup>
		<RootDirectory Condition="'$(RootDirectory)' == ''">$(MSBuildThisFileDirectory)</RootDirectory>
		<SourceDirectory Condition="'$(SourceDirectory)' == ''">$(MSBuildThisFileDirectory)src</SourceDirectory>
		<BuildDirectory Condition="'$(BuildDirectory)' == ''">$(RootDirectory)eng</BuildDirectory>
		<RepositoryFilesDirectory Condition="'$(RepositoryFilesDirectory)' == ''">$(RootDirectory).github</RepositoryFilesDirectory>

		<AppDirectory Condition="'$(AppDirectory)' == ''">$(SourceDirectory)\platforms</AppDirectory>
		<SharedDirectory Condition="'$(SharedDirectory)' == ''">$(SourceDirectory)\core</SharedDirectory>

		<!-- The WASM binary output directory must be relative due to a bug in the SDK, see https://github.com/unoplatform/Uno.Wasm.Bootstrap/issues/1058 -->
		<CIOutputDirectory>$(RootDirectory)bin\$(MSBuildProjectName)\$(Platform)\$(Configuration)\$(TargetFramework)\</CIOutputDirectory>
		<WebOutputDirectory>..\..\..\wwwroot\</WebOutputDirectory> <!--<WebOutputDirectory>$(RootDirectory)wwwroot\</WebOutputDirectory>-->

		<PublishDir>$(CIOutputDirectory)</PublishDir>
		<PublishDir Condition="'$(IsWeb)' == 'true'">$(WebOutputDirectory)</PublishDir>
		<PackageOutputPath>$(PublishDir)</PackageOutputPath>
	</PropertyGroup>

	<!-- Versioning (defined at build) -->
	<PropertyGroup>
		<Product>Elapsed</Product>
		<Company>Hack Club</Company>

		<ReleaseLevel Condition="'$(Configuration)' == 'Debug'">preview</ReleaseLevel>
		<BetaVersion Condition="'$(BetaVersion)' == '' and '$(Configuration)' == 'Debug'">1</BetaVersion>
		<BetaVersion Condition="'$(BetaVersion)' == '' and '$(Configuration)' != 'Debug'">0</BetaVersion>

		<CurrentYear>$([System.DateTime]::Now.ToString("yy"))</CurrentYear>
		<CurrentMonth>$([System.DateTime]::Now.ToString("MM"))</CurrentMonth>
		<CurrentDay>$([System.DateTime]::Now.ToString("dd"))</CurrentDay>
		<BuildDate>$(CurrentYear)$(CurrentMonth)$(CurrentDay)</BuildDate>

		<AssemblyVersion>$(MajorVersion).$(MinorVersion)</AssemblyVersion>
		<BaseDisplayVersion>$(AssemblyVersion).$(BuildDate)</BaseDisplayVersion>

		<ApplicationTitle>$(Product)</ApplicationTitle>
		<ApplicationId>$(MSBuildProjectName)</ApplicationId>
		<ApplicationDisplayVersion>$(AssemblyVersion).$(BetaVersion)</ApplicationDisplayVersion>
		<!--<ApplicationVersion>$(AssemblyVersion).0</ApplicationVersion>-->
		<ApplicationPublisher>$(Company)</ApplicationPublisher>

		<DisplayVersion>$(BaseDisplayVersion)</DisplayVersion>
		<DisplayVersion Condition="'$(ReleaseLevel)' != 'final'">$(BaseDisplayVersion)-$(ReleaseLevel)$(BetaVersion)</DisplayVersion>
		<Version>$(DisplayVersion)</Version>
		<PackageVersion>$(DisplayVersion)</PackageVersion>
	</PropertyGroup>

	<!-- Deterministic build -->
	<PropertyGroup Condition="'$(TF_BUILD)' == 'true' or '$(GITHUB_ACTIONS)' == 'true' or '$(ContinuousIntegrationBuild)' == 'true'">
		<ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
	</PropertyGroup>

	<Target Condition="'$(IsWeb)' == 'true'" Name="CopyWASMBinaryToArtifactDirectory" AfterTargets="Publish">
		<MakeDir Directories="$(CIOutputDirectory)" />
		<ItemGroup>
			<WASMBinary Include="$(WebOutputDirectory)\**\*.*" />
		</ItemGroup>
		<Copy
			SourceFiles="@(WASMBinary)"
			DestinationFolder="$(CIOutputDirectory)%(RecursiveDir)" />
	</Target>

	<ItemGroup>
		<Compile Include="$(SourceDirectory)\GlobalUsings.cs" />
	</ItemGroup>
</Project>
