<Project>
	<PropertyGroup>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
		<IsPackable>true</IsPackable>
		<Title>$(Product)</Title>
		<Authors>Lamparter, ascpixi, Hack Club</Authors>
		<Copyright>Copyright (c) 2026 Lamparter</Copyright>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageIcon>PackageLogo.png</PackageIcon>
		<RepositoryUrl>https://github.com/hackclub/elapsed</RepositoryUrl>
		<RepositoryType>git</RepositoryType>
		<PackageTags>lapse; timelapse; elapsed; uno; unoplatform; windows; android; linux; macos; iphone; hackclub; riverside</PackageTags>
		<Description>Elapsed is Hack Club's new timelapse tracking tool and media sharing platform.</Description>
		<PackageLicenseExpression>MIT</PackageLicenseExpression>
		<PackageRequireLicenseAcceptance>true</PackageRequireLicenseAcceptance>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>
	</PropertyGroup>

	<PropertyGroup>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="10.0.201" PrivateAssets="All"/>
	</ItemGroup>

	<ItemGroup>
		<None Condition="!Exists('$(MSBuildProjectDirectory)\$(PackageReadmeFile)')" Include="$(SourceDirectory)\$(PackageReadmeFile)">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Condition="Exists('$(MSBuildProjectDirectory)\$(PackageReadmeFile)')" Include="$(MSBuildProjectDirectory)\$(PackageReadmeFile)">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Condition="!Exists('$(MSBuildProjectDirectory)\$(PackageIcon)')" Include="$(BuildDirectory)\$(PackageIcon)">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
		<None Condition="Exists('$(MSBuildProjectDirectory)\$(PackageIcon)')" Include="$(MSBuildProjectDirectory)\$(PackageIcon)">
			<Pack>True</Pack>
			<PackagePath>\</PackagePath>
		</None>
	</ItemGroup>
</Project>
