<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<Description>"Riverside.ResumableUploads" is a .NET client for resumable file uploads over the TUS protocol.</Description>

		<TargetFramework>netstandard2.1</TargetFramework>
	</PropertyGroup>

	<ItemGroup>
		<Using Include="OwlCore.Storage" />
	</ItemGroup>

	<ItemGroup>
		<PackageReference Include="Polyfill">
			<PrivateAssets>all</PrivateAssets>
			<IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
		</PackageReference>
		<PackageReference Include="OwlCore.Storage" />
		<PackageReference Include="System.Net.Http.Json" />
		<PackageReference Include="System.Text.Json" />
	</ItemGroup>
</Project>
